### PR TITLE
AA-603: Create Clinic Dashboard Overview Visualization

### PR DESCRIPTION
**Pull request by kimaina**

### CODE REVIEW

**Comment by kimaina** [comment]
https://test1.ampath.or.ke:8443/test-builds/AA-603

**Comment by jonathandick** [comment]
Allan, are you sure that patient status overview is working? I only see
patient's in care.

Can you send me query?

On Thu, Apr 14, 2016 at 7:45 PM, Allan Kimaina notifications@github.com
wrote:

> https://test1.ampath.or.ke:8443/test-builds/AA-603
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/AMPATH/ng-amrs/pull/413#issuecomment-210043782

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by jonathandick** [comment]
Also, the % on ART with VL line is still showing several numbers after the
decimal point.

On Thu, Apr 14, 2016 at 7:51 PM, Jonathan Dick jdick@ampath.or.ke wrote:

> Allan, are you sure that patient status overview is working? I only see
> patient's in care.
> 
> Can you send me query?
> 
> On Thu, Apr 14, 2016 at 7:45 PM, Allan Kimaina notifications@github.com
> wrote:
> 
> > https://test1.ampath.or.ke:8443/test-builds/AA-603
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/AMPATH/ng-amrs/pull/413#issuecomment-210043782
> 
> ## 
> 
> Jonathan Dick, MD
> Chief Medical Information Officer, AMPATH
> Assistant Professor of Clinical Medicine, IU School of Medicine
> Research Scientist, Regenstrief Institute Inc.

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by kimaina** [comment]
please check slack

**Pull request merged**
