### PR TITLE
AA-657 Consume ng-eid Lab Order Viewer From ng-amrs

### PR DESCRIPTION
**Pull request by kimaina**
https://test1.ampath.or.ke:8443/test-builds/AA-656/

Note that you won't be able to fetch data due to https browser security policy of mixed content: The reason eid endpoints are none https (http://eid.ampath.or.ke:85/eid/ and http://41.79.169.130:85/eid/) so you will get this error:

Mixed Content: The page at 'https://test1.ampath.or.ke:8443/test-builds/AA-656/#/patientsearch' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://eid.ampath.or.ke:85/eid/orders/api.php?apikey=35243eba2&currentpage=0&patientID=&test=2'. This request has been blocked; the content must be served over HTTPS

To test this run it locally

### CODE REVIEW

**Comment by mhawila** [comment]
@kimaina Is this authenticating against AMRS?

**Comment by kimaina** [comment]
@mhawila: no, eid api has apikey which is validated on their server

**Comment by kimaina** [comment]
form this request you can see the apikey
http://eid.ampath.or.ke:85/eid/orders/api.php?apikey=35243eba2&currentpage=0&patientID=&test=2

**Comment by jonathandick** [comment]
please note, that this apikey should NOT be published on github!! it allows
access to the eid system. it needs to be a config that is added into the
build.

On Tue, Jun 7, 2016 at 2:52 PM, Allan Kimaina notifications@github.com
wrote:

> form this request you can see the apikey
> 
> http://eid.ampath.or.ke:85/eid/orders/api.php?apikey=35243eba2&currentpage=0&patientID=&test=2
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/AMPATH/ng-amrs/pull/440#issuecomment-224257770, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAIinnCCp3ANRDPDhxqXAibOWd_3YC0Qks5qJVuDgaJpZM4IdI-r
> .

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by jonathandick** [comment]
If we have already published to github, we need to reach out to CHAI to get
a new one (as soon as possible).

On Tue, Jun 7, 2016 at 2:57 PM, Jonathan Dick jdick@ampath.or.ke wrote:

> please note, that this apikey should NOT be published on github!! it
> allows access to the eid system. it needs to be a config that is added into
> the build.
> 
> On Tue, Jun 7, 2016 at 2:52 PM, Allan Kimaina notifications@github.com
> wrote:
> 
> > form this request you can see the apikey
> > 
> > http://eid.ampath.or.ke:85/eid/orders/api.php?apikey=35243eba2&currentpage=0&patientID=&test=2
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/AMPATH/ng-amrs/pull/440#issuecomment-224257770, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/AAIinnCCp3ANRDPDhxqXAibOWd_3YC0Qks5qJVuDgaJpZM4IdI-r
> > .
> 
> ## 
> 
> Jonathan Dick, MD
> Chief Medical Information Officer, AMPATH
> Assistant Professor of Clinical Medicine, IU School of Medicine
> Research Scientist, Regenstrief Institute Inc.

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by kimaina** [comment]
the key has already been published in ng-eid. i have already sent an email to CHAI Team for a new set of apikeys.

**Comment by jonathandick** [comment]
thank you.

On Tue, Jun 7, 2016 at 3:19 PM, Allan Kimaina notifications@github.com
wrote:

> the key has already been published in ng-eid. i have already sent an email
> to CHAI Team for a new set of apikeys.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/AMPATH/ng-amrs/pull/440#issuecomment-224263160, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAIinqsuVcwroZIVRbJiTOOVimZ6tB_oks5qJWHPgaJpZM4IdI-r
> .

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Pull request closed without merging**
