### PR TITLE
AA-589 added relationships on patient dashboard

### PR DESCRIPTION
**Pull request by ellymakuba**

### CODE REVIEW

**Comment by ellymakuba** [comment]
test build link "https://test1.ampath.or.ke:8443/test-builds/AA-589"
try with patient identifiers:821795398-6, 768715925-6 etc

**Comment by jonathandick** [comment]
Elly, a few notes:
1. All names should be capital case, e.g. Familyname Givenname, not
   FAMILYNAME
2. All the relationships which map to existing patients must be clickable
   to the patient dashboard
3. Instead of putting the relationship in () at the end, please put it as:

Father: Givename FamilyName
Mother: Givename FamilyName
1. We need to order these in the most relevant way:
   Parents
   Caretaker
   Siblings
   Cousins
   Grandparents
   Other
2. We need a directive which allows you to create new relatives and edit
   existing ones. For the editing feature, it would be nice to have a "edit"
   next to each relative which allows one to edit from that page.

On Mon, Apr 11, 2016 at 5:10 PM, ellymakuba notifications@github.com
wrote:

> test build link "https://test1.ampath.or.ke:8443/test-builds/AA-589"
> try with patient identifiers:821795398-6, 768715925-6 etc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/AMPATH/ng-amrs/pull/404#issuecomment-208366243

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by jonathandick** [comment]
I forgot to include children:
1. We need to order these in the most relevant way:
   Parents
   Caretaker
   Children
   Siblings
   Cousins
   Grandparents
   Other

On Mon, Apr 11, 2016 at 5:16 PM, Jonathan Dick jdick@ampath.or.ke wrote:

> Elly, a few notes:
> 1. All names should be capital case, e.g. Familyname Givenname, not
>    FAMILYNAME
> 2. All the relationships which map to existing patients must be clickable
>    to the patient dashboard
> 3. Instead of putting the relationship in () at the end, please put it as:
> 
> Father: Givename FamilyName
> Mother: Givename FamilyName
> 1. We need to order these in the most relevant way:
>    Parents
>    Caretaker
>    Siblings
>    Cousins
>    Grandparents
>    Other
> 2. We need a directive which allows you to create new relatives and edit
>    existing ones. For the editing feature, it would be nice to have a "edit"
>    next to each relative which allows one to edit from that page.
> 
> On Mon, Apr 11, 2016 at 5:10 PM, ellymakuba notifications@github.com
> wrote:
> 
> > test build link "https://test1.ampath.or.ke:8443/test-builds/AA-589"
> > try with patient identifiers:821795398-6, 768715925-6 etc
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/AMPATH/ng-amrs/pull/404#issuecomment-208366243
> 
> ## 
> 
> Jonathan Dick, MD
> Chief Medical Information Officer, AMPATH
> Assistant Professor of Clinical Medicine, IU School of Medicine
> Research Scientist, Regenstrief Institute Inc.

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by ellymakuba** [comment]
Noted.

**Pull request merged**
