### PR TITLE
AA-706: Modified notes generation to include all cc/hpi & assessment …

### PR DESCRIPTION
**Pull request by mhawila**
…for all encounters in a given day

### CODE REVIEW

**Comment by mhawila** [comment]
This works with the updated ETL rest server as the version running at 8004 on reporting server.

To test go to
[https://test1.ampath.or.ke:8443/test-builds/AA-706/]

You will have to choose the right version of ETL rest server which is https://amrsreporting.ampath.or.ke:8004/etl/

**Comment by enyachoke** [comment]
I don't seem to be getting notes any good patient

**Comment by mhawila** [comment]
@jonathandick knows the patients with notes. I didn't get anyone with good notes either, just one a two line notes which I can't disclose here because it is a public forum.

**Comment by jonathandick** [comment]
This is close. Please put the provider name next to the encounter type in
the HPI/Assessment table. It's important to know who is saying what.

Please remove italics.

On Wed, Jun 29, 2016 at 1:55 AM, mhawila notifications@github.com wrote:

> Merged #493 https://github.com/AMPATH/ng-amrs/pull/493.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/AMPATH/ng-amrs/pull/493#event-707058437, or mute the
> thread
> https://github.com/notifications/unsubscribe/AAIinkVN_JMy7ICcB1ppXlDMeKHXtSPMks5qQaZygaJpZM4I_V3q
> .

## 

Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Pull request merged**
